### ISSUE TITLE
Feature : enabling audio testing for ad breaks

### ISSUE THREAD

**Issue by rcherp89** [AGulev/defold-poki-sdk#1]
We cannot currently test if the audio gets correctly muted when a commercialBreak or a rewardedBreak is called.

Suggestion : That could be solved by having a background music playing constantly, or having a button to enable/disable a background music.

**Comment by AGulev** [comment]
Hey, I added music in the example. (the sdk itself doesn't handle it, it's up to dev.)
Also, I added an advice in documentation to pause music and sounds.

you can check it here: https://qa.po.ki/#?key=038c0c82-6ee6-4924-b027-94824e464e71
[Defold Poki SDK.zip](https://github.com/AGulev/defold-poki-sdk/files/6447167/Defold.Poki.SDK.zip)
