### ISSUE TITLE
Bug : full screen mode is blocking the ad from being displayed

### ISSUE THREAD

**Issue by rcherp89** [AGulev/defold-poki-sdk#2]
After entering the full screen mode, no ads are displayed after clicking on the buttons. Leaving full screen mode after clicking a button will show the ad being displayed.
That could be caused by the Poki SDK refusing to scale the video ad as well, since the full screen option on poki.com is directly implemented on the poki player, and not by the engine.

**Comment by AGulev** [comment]
@rcherp89 so, that means Poki provides it's own fullscreenn button when it's necessary and users shouldn't use Defold one?

**Comment by AGulev** [comment]
@rcherp89 I've just checked the other games and I see they use a separate button which is not available for developers directly. 
So, I can just add instruction to avoid using of the Defold fullscreen button

**Comment by AGulev** [comment]
maybe it makes sense to add fullscreen button in qa.po.ki page?

**Comment by AGulev** [comment]
Example without the FullScreen button:
[Defold Poki SDK.zip](https://github.com/AGulev/defold-poki-sdk/files/6527942/Defold.Poki.SDK.zip)
https://qa.po.ki/#?key=59c8f10d-b8df-4ee9-ae4f-2a7501ae5bbc
