### ISSUE TITLE
Implement Sharable URLs & URL manipulation

### ISSUE THREAD

**Issue by aglitchman** [AGulev/defold-poki-sdk#3]
Poki introduced new API: [Sharable URLs & URL manipulation](https://sdk.poki.com/html5/#8-sharable-urls-url-manipulation)

It would be great if Defold Poki SDK had an implementation of that new API!

**Comment by AGulev** [comment]
API is ready to be merger in this PR https://github.com/AGulev/defold-poki-sdk/pull/4
But I can't test it at the moment and I'm waiting for help from Poki team in Discord chat about how to test it.

**Comment by aglitchman** [comment]
Great!
